# Generated by Django 4.1.2 on 2022-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulip_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_subjects',
            field=models.ManyToManyField(to='tulip_api_app.subject'),
        ),
    ]
