# Generated by Django 4.1.2 on 2022-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulip_api_app', '0002_remove_teacher_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='student_teachers',
            field=models.ManyToManyField(to='tulip_api_app.teacher'),
        ),
    ]
